import Head from "next/head";

import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

export default function Home() {
  const { user } = useUser();

  const BackgroundSvg = () => {
    return (
      <svg
        className="bg-repeat"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 80 80"
      >
        <path
          fill="#000000"
          fillRule="evenodd"
          d="M11 0l5 20H6l5-20zm42 31a3 3 0 1 0 0-6 3 3 0 0 0 0 6zM0 72h40v4H0v-4zm0-8h31v4H0v-4zm20-16h20v4H20v-4zM0 56h40v4H0v-4zm63-25a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm10 0a3 3 0 1 0 0-6 3 3 0 0 0 0 6zM53 41a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm10 0a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm10 0a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm-30 0a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm-28-8a5 5 0 0 0-10 0h10zm10 0a5 5 0 0 1-10 0h10zM56 5a5 5 0 0 0-10 0h10zm10 0a5 5 0 0 1-10 0h10zm-3 46a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm10 0a3 3 0 1 0 0-6 3 3 0 0 0 0 6zM21 0l5 20H16l5-20zm43 64v-4h-4v4h-4v4h4v4h4v-4h4v-4h-4zM36 13h4v4h-4v-4zm4 4h4v4h-4v-4zm-4 4h4v4h-4v-4zm8-8h4v4h-4v-4z"
        />
      </svg>
    );
  };

  const LandingPage = () => {
    return (
      <div className="relative flex min-h-screen flex-col items-center justify-center overflow-hidden bg-gray-900 font-serif text-white">
        {/* Background Pattern - Replace with your SVG or image pattern */}
        <div className="absolute inset-0 z-0 opacity-10">
          <BackgroundSvg />
        </div>

        <div className="relative z-10 w-2/3 space-y-8 text-center">
          <h1 className="mb-4 text-7xl font-extrabold tracking-tighter">
            Recipe <span className="text-indigo-400">Genius</span>
          </h1>
          <p className="text-lg leading-relaxed text-gray-400">
            Revolutionize your culinary experience with AI.
          </p>
          <p className="text-lg leading-relaxed text-gray-400">
            Craft, innovate, and discover recipes tailored to your ingredients.{" "}
          </p>

          <div className="flex justify-center">
            {!user && (
              <SignInButton>
                <button className="transform rounded-lg bg-gradient-to-r from-indigo-400 to-blue-800 px-8 py-3 font-bold text-white shadow-md transition-transform duration-200 hover:scale-105 hover:from-indigo-600 hover:to-blue-700">
                  Sign In
                </button>
              </SignInButton>
            )}
            {!!user && (
              <SignOutButton>
                <button className="transform rounded-lg bg-gradient-to-r from-indigo-400 to-blue-800 px-8 py-3 font-bold text-white shadow-md transition-transform duration-200 hover:scale-105 hover:from-indigo-600 hover:to-blue-700">
                  Sign Out
                </button>
              </SignOutButton>
            )}
          </div>
        </div>
        <div className="absolute bottom-4 z-10 text-sm text-gray-500">
          © 2023 Recipe Genius. All rights reserved.
        </div>
      </div>
    );
  };

  const Dashboard = () => {
    if (!user) return null;
    return (
      <>
        <Head>
          <title>Dashboard</title>
        </Head>
        <main>
          <h1>Dashboard</h1>
          <p>Hi, {user.fullName}</p>
          <SignOutButton>
            <button className="transform rounded-lg bg-gradient-to-r from-indigo-400 to-blue-800 px-8 py-3 font-bold text-white shadow-md transition-transform duration-200 hover:scale-105 hover:from-indigo-600 hover:to-blue-700">
              Sign Out
            </button>
          </SignOutButton>
        </main>
      </>
    );
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!user && <LandingPage />}
      {!!user && <Dashboard />}
    </>
  );
}
